<a href="https://colab.research.google.com/github/manalrizwan02-cloud/EDA-Projects-/blob/EDA-Visualization/EDA_E_commerce_sales_data_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_csv("/content/ecommerce_sales_data.csv")
df

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07
...,...,...,...,...,...,...,...,...,...
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29
997,2021,January,Electronics,North,85,14304.92,2047.38,2.1,370.55
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75
999,2021,October,Beauty Products,North,211,19643.44,2722.46,1.5,218.01

In [6]:
df.shape

(1000, 9)

In [7]:
df.head()

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07

In [8]:
df.tail()

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29
997,2021,January,Electronics,North,85,14304.92,2047.38,2.1,370.55
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75
999,2021,October,Beauty Products,North,211,19643.44,2722.46,1.5,218.01

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             1000 non-null   int64
 1   Month            1000 non-null   object
 2   Category         1000 non-null   object
 3   Region           1000 non-null   object
 4   Units_Sold       1000 non-null   int64
 5   Revenue          1000 non-null   float64
 6   Profit           1000 non-null   float64
 7   Customer_Rating  1000 non-null   float64
 8   Ad_Spend         1000 non-null   float64
dtypes: float64(4), int64(2), object(3)
memory usage: 70.4+ KB

In [10]:
df.describe()

,Year,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2021.955000,263.337000,27123.544520,5494.732660,3.040200,2649.554610
std,1.367057,137.701086,22261.011837,5041.842396,1.161599,1408.662125
min,2020.000000,20.000000,541.780000,83.910000,1.000000,101.940000
25%,2021.000000,138.000000,8451.205000,1612.855000,2.000000,1429.070000
50%,2022.000000,268.500000,20743.015000,3820.585000,3.100000,2724.605000
75%,2023.000000,381.250000,41275.547500,7989.782500,4.000000,3888.252500
max,2024.000000,500.000000,96923.930000,25675.500000,5.000000,4997.660000

In [11]:
df.columns

Index(['Year', 'Month', 'Category', 'Region', 'Units_Sold', 'Revenue',
       'Profit', 'Customer_Rating', 'Ad_Spend'],
      dtype='object')

In [12]:
df.dtypes

Year                 int64
Month               object
Category            object
Region              object
Units_Sold           int64
Revenue            float64
Profit             float64
Customer_Rating    float64
Ad_Spend           float64
dtype: object

In [13]:
df.isnull().sum()

Year               0
Month              0
Category           0
Region             0
Units_Sold         0
Revenue            0
Profit             0
Customer_Rating    0
Ad_Spend           0
dtype: int64

In [14]:
df.isnull().any().sum()

np.int64(0)

In [15]:
df.T.duplicated()

Year               False
Month              False
Category           False
Region             False
Units_Sold         False
Revenue            False
Profit             False
Customer_Rating    False
Ad_Spend           False
dtype: bool

In [16]:
df['Date'] = pd.to_datetime(
    df['Year'].astype(str) + '-' + df['Month'],
    format='%Y-%B'
)
df['Date']

0     2020-04-01
1     2021-10-01
2     2022-02-01
3     2020-04-01
4     2020-09-01
         ...
995   2023-01-01
996   2024-10-01
997   2021-01-01
998   2024-05-01
999   2021-10-01
Name: Date, Length: 1000, dtype: datetime64[ns]

In [17]:
df

,Year,Month,Category,Region,Units_Sold,Revenue,Profit,Customer_Rating,Ad_Spend,Date
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51,2020-04-01
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18,2021-10-01
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31,2022-02-01
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92,2020-04-01
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07,2020-09-01
...,...,...,...,...,...,...,...,...,...,...
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84,2023-01-01
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29,2024-10-01
997,2021,January,Electronics,North,85,14304.92,2047.38,2.1,370.55,2021-01-01
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75,2024-05-01
999,2021,October,Beauty Products,North,211,19643.44,2722.46,1.5,218.01,2021-10-01

In [18]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [19]:
df

,year,month,category,region,units_sold,revenue,profit,customer_rating,ad_spend,date
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51,2020-04-01
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18,2021-10-01
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31,2022-02-01
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92,2020-04-01
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07,2020-09-01
...,...,...,...,...,...,...,...,...,...,...
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84,2023-01-01
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29,2024-10-01
997,2021,January,Electronics,North,85,14304.92,2047.38,2.1,370.55,2021-01-01
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75,2024-05-01
999,2021,October,Beauty Products,North,211,19643.44,2722.46,1.5,218.01,2021-10-01

In [20]:
df["total_cost"] = df["revenue"] - df["profit"]
df["unit_price"] = df["total_cost"] / df["units_sold"]
df["profit_margin"] = (
    df["profit"] / df["revenue"]
) * 100

In [21]:
df

,year,month,category,region,units_sold,revenue,profit,customer_rating,ad_spend,date,total_cost,unit_price,profit_margin
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51,2020-04-01,68918.19,142.099361,26.962944
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18,2021-10-01,10624.17,111.833368,24.551749
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31,2022-02-01,9714.89,53.378516,29.090982
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92,2020-04-01,61129.55,145.893914,25.320834
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07,2020-09-01,46186.29,98.478230,10.855193
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84,2023-01-01,4028.89,106.023421,28.134331
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29,2024-10-01,10845.77,25.700877,19.741044
997,2021,January,Electronics,North,85,14304.92,2047.38,2.1,370.55,2021-01-01,12257.54,144.206353,14.312418
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75,2024-05-01,52320.39,120.553894,21.841880
999,2021,October,Beauty Products,North,211,19643.44,2722.46,1.5,218.01,2021-10-01,16920.98,80.194218,13.859385

In [22]:
df["month_name"] = df["date"].dt.month_name()
df["day"] = df["date"].dt.day
df["day_name"] = df["date"].dt.day_name()
df["quarter"] = df["date"].dt.quarter

In [23]:
df

,year,month,category,region,units_sold,revenue,profit,customer_rating,ad_spend,date,total_cost,unit_price,profit_margin,month_name,day,day_name,quarter
0,2020,April,Home Decor,North,485,94360.58,25442.39,1.5,174.51,2020-04-01,68918.19,142.099361,26.962944,April,1,Wednesday,2
1,2021,October,Fashion,South,95,14081.40,3457.23,3.5,3975.18,2021-10-01,10624.17,111.833368,24.551749,October,1,Friday,4
2,2022,February,Groceries,East,182,13700.50,3985.61,3.4,1929.31,2022-02-01,9714.89,53.378516,29.090982,February,1,Tuesday,1
3,2020,April,Fashion,South,419,81856.23,20726.68,2.8,3706.92,2020-04-01,61129.55,145.893914,25.320834,April,1,Wednesday,2
4,2020,September,Beauty Products,North,469,51810.41,5624.12,2.9,2362.07,2020-09-01,46186.29,98.478230,10.855193,September,1,Tuesday,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,January,Fashion,West,38,5606.14,1577.25,3.2,4788.84,2023-01-01,4028.89,106.023421,28.134331,January,1,Sunday,1
996,2024,October,Groceries,East,422,13513.47,2667.70,3.1,495.29,2024-10-01,10845.77,25.700877,19.741044,October,1,Tuesday,4
997,2021,January,Electronics,North,85,14304.92,2047.38,2.1,370.55,2021-01-01,12257.54,144.206353,14.312418,January,1,Friday,1
998,2024,May,Groceries,South,434,66941.72,14621.33,2.5,2944.75,2024-05-01,52320.39,120.553894,21.841880,May,1,Wednesday,2
999,2021,October,Beauty Products,North,211,19643.44,2722.46,1.5,218.01,2021-10-01,16920.98,80.194218,13.859385,October,1,Friday,4

In [24]:
df.isnull().sum()

year               0
month              0
category           0
region             0
units_sold         0
revenue            0
profit             0
customer_rating    0
ad_spend           0
date               0
total_cost         0
unit_price         0
profit_margin      0
month_name         0
day                0
day_name           0
quarter            0
dtype: int64

In [25]:
df.shape

(1000, 17)

In [44]:
df['time'] = pd.to_datatime(df['time'], format='%H:%M:%S', errors='coerce').dt.time
df.info()

AttributeError: module 'pandas' has no attribute 'to_datatime'

In [43]:
df['date'] = pd.to_datetime(df['date'])

df['time'] = df['date'].dt.time

TypeError: 'NoneType' object is not subscriptable

In [41]:
df['time'] = pd.to_datetime(
    df['time'],
    format='%H:%M:%S',
    errors='coerce'
).dt.time

df.info()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
data['time'].unique()